---
title: "Gender Inclusivity in Statistics and Data Science Education: Project Page"
output: rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmdformats)
```

# Project Contributors

In alphabetical order: 

- [Eric Friedlander](https://www.snc.edu/academics/faculty/eric.friedlander.html)
- [Jax Mader](https://www.math.purdue.edu/people/grad/index.html?student=lmader)
- [V.N. Vimal Rao](https://raovnv.github.io/research.html)

# Introduction to the Project

Gender is a non-binary construct. However, our textbooks and activities still typically define gender as either “man” or “woman”, and often conflate gender with biological sex (i.e., “male” and “female”). Presently, even if teachers wanted to use gender inclusive datasets and activities, there are little to no resources for them to do so. This project aims to rectify that by acquiring gender inclusive datasets and by creating activities and lesson plans based on these datasets. To ensure that the activities indeed serve to include all individuals, we employ a participatory design-based research method, including individuals with non-cisgender identities from the onset of the project. 

# Funding

This project is generously supported by a grant from the Association for Psychological Science's Fund for Teaching and Public Understanding of Psychological Science. 

# Project Goals

Our project has three main objectives: 

- develop a framework for the development of gender inclusive activities by conducting interviews and focus groups with non-cisgender statistics and data science students
- develop activities to promote gender inclusivity in statistics and data science classrooms by utilizing a participatory design based research method
- develop assessment tools to measure gender inclusivity in statistics and data science classrooms by utilizing methods for test development consistent with the Standards for Educational and Psychological Testing

# Current Status

Framework development: 

- We have completed creating a framework to support the design of gender inclusive activities. 

Activity development: 

- We have completed developing the first version of our activities. 
- We have completed piloting the first version of our activities in a small classroom (~ 20 students). 
- We are currently working on evaluating the results of this pilot implementation, and will soon begin revising the activities based on these evaluations. 
- We will next implement our revised activities in one small classroom (~ 20 students) and one large classroom (~ 600 students). 

Assessment development: 

- We have created a test blueprint and a first version of our assessment. 
- We have completed piloting the first version of our assessment in a small classroom. 
- We are currently working on evaluating the results of this pilot implementation, and will soon begin revising the assessment based on these evaluations. 
- We will next implement our revised assessment in one small classroom (~ 20 students) and one large classroom (~ 600 students), as well as conduct cognitive interviews. 


# Publications

- Rao, V.N.V., Mader, J., & Friedlander, E. (2023). A framework for the design of gender inclusive activities. In E.M. Jones (Ed.), *Fostering Learning of Statistics and Data Science: Proceedings of the Satellite Conference of the International Association for Statistical Education.* Available at [https://iase-web.org/Webinars.php?p=230711_2000](https://iase-web.org/Webinars.php?p=230711_2000).


# Conference Presentations

USCOTS 2023

- Rao, V.N.V., Mader, J., & Friedlander, E. (2023, June). *[Gender Inclusivity from the Perspective of Non-Cisgender Students](https://causeweb.org/cause/uscots/uscots23/gender-inclusivity-perspective-non-cisgender-students)*. [Lightning Talk]. Consortium for the Advancement of Undergraduate Statistics Education (CAUSE) Research Satellite, State College, Pennsylvania.

- Friedlander, E., Mader, J., & Rao, V.N.V. (2023, June). *[Gender Inclusive Activities in an Introductory Statistics Class](https://causeweb.org/cause/uscots/uscots23/f02-gender-inclusive-activities-introductory-statistics-class)* [Posters and Beyond Presentation]. United States Conference on Teaching Statistics (USCOTS), State College, PA, USA.

- Rao, V.N.V., Mader, J., & Friedlander, E. (2023, June). *[Gender Inclusivity from the Perspective of Non-Cisgender Students](https://causeweb.org/cause/uscots/uscots23/f03-gender-inclusivity-perspective-non-cisgender-students)* [Poster Presentation]. Consortium for the Advancement of Undergraduate Statistics Education (CAUSE) Research Satellite, State College, PA, USA.



IASE 2023 Satellite

- Rao, V.N.V., Mader, J., & Friedlander, E. (2023, July). A framework for the design of gender inclusive activities [Paper Presentation]. 13th Annual Satellite Conference of the International Association for Statistical Education (IASE), Toronto, Ontario, Canada.


PsychTERMS 2023 

- Rao, V.N.V., Mader, J., & Friedlander, E. (2023, December). *[Gender Inclusive Activities and Datasets for Introductory Level Statistics](https://www.psychterms.com/2023-program)* [Poster Presentation]. Teaching to Enhance Research Methods & Statistics in Psychology (PsychTERMS) 2023 Virtual Conference, online. 


APS 2024 

- Rao, V.N.V., Mader, J., & Friedlander, E. (2024, May). *A framework for the design of gender inclusive activies* [Poster Presentation]. Annual Meeting of the American Psychological Society (APS), San Francisco, CA, USA.
